### PR TITLE
updates for mail@2.7.0 compatibility

### LINKED ISSUE #4: IndexError: string not matched
Works fine with mail 2.6.6, but with mail 2.7.0 I started getting this error,
here is cleaned up trace from my log, this is ruby 2.4.1 rails 5.0.6

WARN: IndexError: string not matched
.../gems/mail-x_smtpapi-1.1.0/lib/mail_x_smtpapi/accessors.rb:48:in `[]='
.../gems/mail-x_smtpapi-1.1.0/lib/mail_x_smtpapi/accessors.rb:48:in `category='
.../gems/mail-2.7.0/lib/mail/field.rb:237:in `method_missing'

### PR DESCRIPTION
**Pull request by cainlevy**
`Mail::Field#value` is now actively coerced into either an array or string, so `mail-x_smtpapi` must use a different accessor for its data hash.

This also adds Appraisal for testing against both 2.6 and 2.7.

Fixes #4

### CODE REVIEW

**Comment by cainlevy** [comment]
I'm no longer a maintainer of the repository, but I'm the sole owner of the rubygem. If any current maintainer would like publishing permissions, please contact me.

**Comment by tiegz** [comment]
@cainlevy thanks, recently ran into this too! 

If people upgraded `mail` and `mail-x_smtpapi` they might miss the `value->data` change. Think it's worth adding a CHANGELOG with a note about the breaking change? (I'm happy go write up a changelog on this branch too!)

**Comment by cainlevy** [comment]
@tiegz couldn't hurt to add a note! i forget if `value` was something people might reasonably have accessed before? it almost looked like a private implementation detail.

**Comment by tiegz** [comment]
@cainlevy I was wondering that too! We call `value` directly in a few places, but I'm not sure why we do that instead of calling the methods like `to` directly. 😬 

(I'll do a separate PR for the changelog in a bit!)

**Comment by tiegz** [comment]
Ok, Changelog is [alive](https://github.com/kickstarter/mail-x_smtpapi/blob/master/CHANGELOG.md)! 

@cainlevy should we do a 2.* version with a `Breaking changes` section, or do you think this falls under "implementation changes" and we could do a 1.2 release?

**Comment by cainlevy** [comment]
I'd be inclined to call this an implementation change. Maybe even a bug fix? Your call though!

**Comment by tiegz** [comment]
👍 cool, implementation change sounds reasonable.

**Review by tiegz — APPROVED** [review]
👍

**Comment by cainlevy** [comment]
Is this ready to go? I'm unable to merge.

**Comment by tiegz** [comment]
Doh, sorry @cainlevy ! Merging now 👍

**Pull request merged**
